# Generated by Django 4.2.11 on 2024-04-17 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_rename_prise_products_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='descount',
            new_name='discount',
        ),
    ]
